---
abstract: 'Parse Service Centre time-stamp DDMMYYhhmmss format'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-SCTS
provides:
  DateTime::Format::SCTS:
    file: lib/DateTime/Format/SCTS.pm
    version: 0.01
requires:
  DateTime::Format::Builder: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime-Format-SCTS
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/perl-DateTime-Format-SCTS
version: 0.01
